apiVersion: apps/v1
kind: Deployment
metadata:
  name: svk-swapi-planets-api
  namespace: ${namespace}
  labels:
    app: ${planets_manifest_app_name}
  annotations:
    ves.io/workload-flavor: tiny
    ves.io/virtual-sites: ${namespace}/s-vankalken-vs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${planets_manifest_app_name}
  template:
    metadata:
      labels:
        app: ${planets_manifest_app_name}
    spec:
      containers:
      - image: public.ecr.aws/y6q2t0j9/demos:swapi-api
        imagePullPolicy: IfNotPresent
        name: ${planets_manifest_app_name}
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ${planets_servicename}
  labels:
    app: ${planets_manifest_app_name}
spec:
  type: ClusterIP
  selector:
    app: ${planets_manifest_app_name}
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
