apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unit-pvc
  namespace: s-vankalken
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  
